cookbook 'postgresql'#,  git: 'https://github.com/opscode-cookbooks/postgresql.git'
cookbook 'python'#,      git: 'https://github.com/opscode-cookbooks/python.git'
#cookbook 'chef-base',           git:  'https://github.com/captnswing/chef-base.git'
#cookbook 'chef-msttcorefonts',  git:  'https://github.com/captnswing/chef-msttcorefonts'
cookbook 'chef-base',           path: '/Users/frank/Development/chef-cookbooks/chef-base'
cookbook 'chef-msttcorefonts',  path: '/Users/frank/Development/chef-cookbooks/chef-msttcorefonts'
cookbook 'webscreenshots',      path: '/Users/frank/Development/chef-cookbooks/chef-webscreenshots'
