cookbook 'nginx',               git:    'https://github.com/opscode-cookbooks/nginx'
cookbook 'python',              git:    'https://github.com/opscode-cookbooks/python.git'
cookbook 'postgresql',          git:    'https://github.com/opscode-cookbooks/postgresql.git'
cookbook 'chef-base',           git:    'https://github.com/captnswing/chef-base.git'
cookbook 'chef-msttcorefonts',  git:    'https://github.com/captnswing/chef-msttcorefonts'
cookbook 'chef-webscreenshots', git:    'https://github.com/captnswing/chef-webscreenshots'
