cookbook 'python',      git: 'https://github.com/opscode-cookbooks/python.git'
#cookbook 'chef-base',   git: 'https://github.com/captnswing/chef-base.git'
cookbook 'chef-base',    path: '/Users/frank/Development/chef-cookbooks/chef-base'
#cookbook 'redis',       git: 'https://github.com/captnswing/redis-cookbook'
cookbook 'redis',       path: '/Users/frank/Development/chef-cookbooks/redis'
cookbook 'postgresql',  git: 'https://github.com/opscode-cookbooks/postgresql.git'
