web:
  build: .
  environment:
    - AWS_ACCESS_KEY
    - AWS_SECRET_KEY
    - PYTHONPATH=.
    - DJANGO_SETTINGS_MODULE=webscreenshots.settings.docker
  command: bash -c "python ./webscreenshots/manage.py migrate && ./webscreenshots/manage.py runserver 0.0.0.0:5000"
  volumes:
    - .:/code/
  ports:
    - "5000"
  links:
    - db
#dbdata:
#  image: postgres:latest
#  volumes:
#    - /var/lib/postgresql
#  command: true
db:
  image: postgres:latest
#  volumes_from:
#    - dbdata
  ports:
    - "5432"
  environment:
    - USER=postgres
    - DB=postgres
redis:
  image: redis
rabbitmq:
  image: rabbitmq
