- name: install dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - libxml2-dev
    - libxslt1-dev
    - cython
    - postgresql-server-dev-all
    - python-dev
    - redis-server

- name: create {{ ws_home }} directory
  shell: sudo mkdir -p {{ ws_home }}; sudo chown -R ws:ws {{ ws_home }}
         creates={{ ws_home }}

- name: create virtualenv in {{ ws_home }}
  shell: virtualenv {{ ws_home }}
         creates={{ ws_home }}/bin/activate

- name: install supervisor
  pip: name=supervisor
       virtualenv={{ ws_home }}

- name: install celery
  pip: name=celery
       virtualenv={{ ws_home }}

- name: create subdirectories in {{ ws_home }}
  file: path={{ item }}
        state=directory
        recurse=yes
        owner=ws
        group=ws
  with_items:
    - '{{ ws_home }}'
    - '{{ ws_home }}/etc/supervisor/conf.d'
    - '{{ ws_home }}/var/log'
    - '{{ ws_home }}/var/run'

- name: installing celeryd configuration for supervisor
  template: src={{ item.src }} dest={{ item.dest }} mode=644
  with_items:
    - { src: 'celeryd.ini.j2', dest: '{{ ws_home }}/etc/supervisor/conf.d/celeryd.ini' }
    - { src: 'redis.ini.j2', dest: '{{ ws_home }}/etc/supervisor/conf.d/redis.ini' }
#  notify: reload supervisor jobs

- name: installing supervisor init script
  template: src=supervisord_init.j2
            dest={{ ws_home }}/etc/supervisor/supervisord_init.sh
            mode=755
  notify: reload supervisord

- name: installing supervisor configuration
  template: src=supervisord.conf.j2
            dest={{ ws_home }}/etc/supervisor/supervisord.conf
            mode=644
  notify: reload supervisord
