- name: add ws user
  user: name=ws password=ws comment=webscreenshots home={{ ws_home }} shell=/bin/bash

- name: mkdir {{ ws_home }}
  file: path={{ ws_home }} state=directory recurse=yes owner=ws group=ws

